import 'package:flutter/material.dart';
import '../../../core/services/admin_settings_service.dart';

class SettingsScreenV2 extends StatefulWidget { const SettingsScreenV2({super.key}); @override State<SettingsScreenV2> createState()=>_SettingsScreenV2State(); }
class _SettingsScreenV2State extends State<SettingsScreenV2>{
 final _svc=AdminSettingsService(); late Future<List<dynamic>> _future;
 AdminSettings? _a; StudentAppSettings? _s; bool saving=false; String theme='system'; bool compact=false,analytics=true,maintenance=false,registration=true,notifications=true,forceUpdate=false;
 final appName=TextEditingController(),appVersion=TextEditingController(),maintMsg=TextEditingController(),announcement=TextEditingController(),minVersion=TextEditingController(),supportEmail=TextEditingController();
 @override void initState(){super.initState();_future=_load();}
 @override void dispose(){for(final c in [appName,appVersion,maintMsg,announcement,minVersion,supportEmail]){c.dispose();}super.dispose();}
 Future<List<dynamic>> _load()=>Future.wait([_svc.getAdminSettings(),_svc.getStudentSettings()]);
 void _fill(List<dynamic> d){if(_a!=null)return;_a=d[0];_s=d[1];theme=_a!.themeMode;compact=_a!.sidebarCompact;analytics=_a!.analyticsEnabled;appName.text=_s!.appName;appVersion.text=_s!.appVersion;maintenance=_s!.maintenanceMode;maintMsg.text=_s!.maintenanceMessage;registration=_s!.allowRegistration;notifications=_s!.notificationsEnabled;announcement.text=_s!.homeAnnouncement;minVersion.text=_s!.minimumSupportedVersion;forceUpdate=_s!.forceUpdate;supportEmail.text=_s!.supportEmail;}
 Future<void> _save()async{if(_a==null||_s==null)return;setState(()=>saving=true);try{await Future.wait([_svc.updateAdminSettings(id:_a!.id,themeMode:theme,sidebarCompact:compact,analyticsEnabled:analytics),_svc.updateStudentSettings(id:_s!.id,maintenanceMode:maintenance,maintenanceMessage:maintMsg.text.trim(),allowRegistration:registration,notificationsEnabled:notifications,homeAnnouncement:announcement.text.trim(),minimumSupportedVersion:minVersion.text.trim(),forceUpdate:forceUpdate,supportEmail:supportEmail.text.trim(),appName:appName.text.trim().isEmpty?'MediData':appName.text.trim(),appVersion:appVersion.text.trim().isEmpty?'1.0.0':appVersion.text.trim())]);if(!mounted)return;setState(()=>saving=false);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Settings saved. Restart the affected app/dashboard to apply global changes.')));}catch(e){if(mounted){setState(()=>saving=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Save failed: $e')));}}}
 @override Widget build(BuildContext c){final t=Theme.of(c),s=t.colorScheme;return Material(color:s.surface,child:FutureBuilder<List<dynamic>>(future:_future,builder:(c,x){if(x.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(x.hasError||x.data==null)return Center(child:FilledButton.icon(onPressed:()=>setState(()=>_future=_load()),icon:const Icon(Icons.refresh),label:const Text('Try Again')));_fill(x.data!);return ListView(padding:const EdgeInsets.fromLTRB(24,20,24,32),children:[Text('Settings',style:t.textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:6),Text('Control the Admin Dashboard and MediData student app centrally.',style:t.textTheme.bodyMedium?.copyWith(color:s.onSurfaceVariant)),const SizedBox(height:20),_card(c,'Admin Dashboard',[DropdownButtonFormField<String>(initialValue:theme,decoration:const InputDecoration(labelText:'Theme Mode'),items:const[DropdownMenuItem(value:'system',child:Text('System')),DropdownMenuItem(value:'light',child:Text('Light')),DropdownMenuItem(value:'dark',child:Text('Dark'))],onChanged:saving?null:(v)=>setState(()=>theme=v??'system')),SwitchListTile.adaptive(title:const Text('Compact Sidebar'),value:compact,onChanged:saving?null:(v)=>setState(()=>compact=v)),SwitchListTile.adaptive(title:const Text('Analytics'),value:analytics,onChanged:saving?null:(v)=>setState(()=>analytics=v))]),const SizedBox(height:16),_card(c,'Student App',[TextField(controller:appName,decoration:const InputDecoration(labelText:'App Name')),const SizedBox(height:10),TextField(controller:appVersion,decoration:const InputDecoration(labelText:'App Version')),SwitchListTile.adaptive(title:const Text('Maintenance Mode'),value:maintenance,onChanged:saving?null:(v)=>setState(()=>maintenance=v)),if(maintenance)TextField(controller:maintMsg,maxLines:3,decoration:const InputDecoration(labelText:'Maintenance Message')),SwitchListTile.adaptive(title:const Text('Allow Registration'),value:registration,onChanged:saving?null:(v)=>setState(()=>registration=v)),SwitchListTile.adaptive(title:const Text('Push Notifications'),value:notifications,onChanged:saving?null:(v)=>setState(()=>notifications=v)),TextField(controller:announcement,maxLines:2,decoration:const InputDecoration(labelText:'Home Announcement')),const SizedBox(height:10),TextField(controller:minVersion,decoration:const InputDecoration(labelText:'Minimum Supported Version')),SwitchListTile.adaptive(title:const Text('Force Update'),value:forceUpdate,onChanged:saving?null:(v)=>setState(()=>forceUpdate=v)),TextField(controller:supportEmail,decoration:const InputDecoration(labelText:'Support Email'))]),const SizedBox(height:18),FilledButton.icon(onPressed:saving?null:_save,icon:saving?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.save),label:Text(saving?'Saving...':'Save All Settings'))]);}));}
 Widget _card(BuildContext c,String title,List<Widget> children)=>Card(elevation:0,child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w700)),const SizedBox(height:14),...children])));
}